### PR TITLE
move "fresque.ini" to "config/fresque.ini.sample"

### PR DESCRIPTION
**Pull request by hoomanna**
in order to be composer friendly we must put a sample file for config
cause after run "composer update" the changes will be overwritten.

### CODE REVIEW

**Comment by RTLer** [comment]
@kamisama could you please merge this?

Regards,

**Comment by wa0x6e** [comment]
There's something weird with this PR, the changes are missing.

**Comment by glensc** [comment]
@wa0x6e i  think he did not realize pushing to branch would also update github, and seems he doesn't even read the github notifications. as you can see he created his PR from 'master' branch, not 'feature-branch'.

so use commandline and merge only first commit perhaps?
(commands offered by github "use commandline link")
(...)
(git reset --hard 9ad963ccee06a273cdf82a6cefa2247f1f4ecfe0)

**Comment by amiri27** [comment]
@wa0x6e I know the guy which made the PR.. Do you want to Resend a PR again?

**Comment by hoomanna** [comment]
when i was used Fresque in a project for first time and it was hard thing to deal with `fresque.ini` file in vendor 
this PR moved the file into `config/fresque.ini.sample` so the real file stay unharmed by composer update
but as you know it's not good idea and Fresque command have option to set config path 
and sorry for delay

**Pull request closed without merging**
